In [1]:
import tensorflow as tf
import numpy as np

지금까지는 메모리에 들어갈 수 있는 데이터만 사용했다. 하지만 메모리 용량에 맞지 않는 아주 큰 규모의 데이터셋으로 딥러닝 시스템을 훈련해야 하는 경우가 많다. 다른 딥러닝 라이브러리를 사용해서는 대규모 데이터셋을 효율적으로 로드하고 전처리하기 어렵다. 하지만 텐서츨로는 데이터 API덕분에 이를 쉽게 처리할 수 있다. 

# 데이터 API

In [15]:
X = tf.range(10)
dataset = tf.data.Dataset.from_tensor_slices(X)
dataset

<TensorSliceDataset element_spec=TensorSpec(shape=(), dtype=tf.int32, name=None)>

> from_tensor_slices()

함수는 텐서를 받아 *첫 번째 차원을 따라) X의 각 원소가 아이템으로 표현되는 tf.data.Dataset을 만든다. <br>
즉 이 데이터셋은 텐서 0,1,2,...,9에 해당하는 10개의 아이템을 가진다. 이 경우 tf.data.Dataset.range(10)로 만든 데이터셋과 동일하다.

아래와 같이 데이터셋의 아이템을 순회할 수 있다.

In [16]:
for item in dataset:
    print(item)

tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(5, shape=(), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)
tf.Tensor(7, shape=(), dtype=int32)
tf.Tensor(8, shape=(), dtype=int32)
tf.Tensor(9, shape=(), dtype=int32)


# 연쇄변환

데이터셋이 준비디면 변환 메서드를 호출하여 여러 종류의 변환을 수행할 수 있다. 각 메서드는 새로운 데이터셋을 반환하므로 다음과 같이 변환 메서드를 연결할 수 있다. 

In [17]:
# drop_remainder = True로 설정하면 사이즈가 7이 안되는 아이템은 버려진다.
dataset = dataset.repeat(3).batch(7)
for item in dataset:
    print(item)
    
# 데이터셋을 3번 반복하게 하고, 배치사이즈를 7로 설정한 데이터셋을 반환한다.

tf.Tensor([0 1 2 3 4 5 6], shape=(7,), dtype=int32)
tf.Tensor([7 8 9 0 1 2 3], shape=(7,), dtype=int32)
tf.Tensor([4 5 6 7 8 9 0], shape=(7,), dtype=int32)
tf.Tensor([1 2 3 4 5 6 7], shape=(7,), dtype=int32)
tf.Tensor([8 9], shape=(2,), dtype=int32)


In [19]:
# map 함수를 통한 전처리
dataset= dataset.map(lambda x : x*2)

In [20]:
for item in dataset:
    print(item)

tf.Tensor([ 0  2  4  6  8 10 12], shape=(7,), dtype=int32)
tf.Tensor([14 16 18  0  2  4  6], shape=(7,), dtype=int32)
tf.Tensor([ 8 10 12 14 16 18  0], shape=(7,), dtype=int32)
tf.Tensor([ 2  4  6  8 10 12 14], shape=(7,), dtype=int32)
tf.Tensor([16 18], shape=(2,), dtype=int32)


In [22]:
# 각 item에 적용되는 map함수와 달리 apply함수는 데이터셋 전체에 변환을 적용한다.
dataset = dataset.apply(tf.data.experimental.unbatch())

Instructions for updating:
Use `tf.data.Dataset.unbatch()`.


In [25]:
for item in dataset:
    print(item)

tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)
tf.Tensor(8, shape=(), dtype=int32)
tf.Tensor(10, shape=(), dtype=int32)
tf.Tensor(12, shape=(), dtype=int32)
tf.Tensor(14, shape=(), dtype=int32)
tf.Tensor(16, shape=(), dtype=int32)
tf.Tensor(18, shape=(), dtype=int32)
tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)
tf.Tensor(8, shape=(), dtype=int32)
tf.Tensor(10, shape=(), dtype=int32)
tf.Tensor(12, shape=(), dtype=int32)
tf.Tensor(14, shape=(), dtype=int32)
tf.Tensor(16, shape=(), dtype=int32)
tf.Tensor(18, shape=(), dtype=int32)
tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)
tf.Tensor(8, shape=(), dtype=int32)
tf.Tensor(10, shape=(), dtype=int32)
tf.Tensor(12, shape=(), dtype=int32)
tf.Tensor(14, sh

In [26]:
# filter 메서드를 사용해서 데이터셋을 필터링
dataset = dataset.filter(lambda x: x>10)

In [28]:
# take 메서드를 사용해서 데이터셋 몇개만 보기
for item in dataset.take(3):
    print(item)

tf.Tensor(12, shape=(), dtype=int32)
tf.Tensor(14, shape=(), dtype=int32)
tf.Tensor(16, shape=(), dtype=int32)


# 데이터 셔플링

--------------

이 파트 공부를 하는데 잘 모르겠기도 하고, 당장 내가 쓸수 있는 내용은 아닌 것 같다. 그래서 다음으로 미루겠다...

다른사람들도 pd.read_csv를 통해서 데이터를 적재하는 것 같다..!! 